### PR TITLE
Feature unomi 5 karaf4 1

### PR DESCRIPTION
**Pull request by oliverlietz**

### CODE REVIEW

**Comment by oliverlietz** [comment]
```
Initializing Unomi...
[2018-03-06T00:40:10,676][INFO ][o.e.c.m.MetaDataCreateIndexService] [JHSGgjI] [context] creating index, cause [api], templates [], shards [5]/[0], mappings [_default_, scoring, goal, userList, personaSession, profile, propertyType, segment, campaignevent, rule, campaign]
[2018-03-06T00:40:10,849][INFO ][o.e.c.r.a.AllocationService] [JHSGgjI] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[context][4]] ...]).
[2018-03-06T00:40:12,872][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] create_mapping [actionType]
[2018-03-06T00:40:12,973][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] create_mapping [conditionType]
[2018-03-06T00:40:13,039][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,166][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,244][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,283][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,337][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,382][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,416][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [conditionType]
[2018-03-06T00:40:13,537][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [actionType]
[2018-03-06T00:40:13,793][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [rule]
[2018-03-06T00:40:13,838][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [rule]
[2018-03-06T00:40:13,865][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [rule]
[2018-03-06T00:40:13,890][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [rule]
[2018-03-06T00:40:13,918][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [rule]
[2018-03-06T00:40:14,110][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] create_mapping [persona]
[2018-03-06T00:40:14,147][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [personaSession]
[2018-03-06T00:40:14,204][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [propertyType]
[2018-03-06T00:40:14,278][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [propertyType]
[2018-03-06T00:40:14,306][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [propertyType]
[2018-03-06T00:40:14,359][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [propertyType]
[2018-03-06T00:40:14,435][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [propertyType]
[2018-03-06T00:40:14,680][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [profile]
[2018-03-06T00:40:15,022][INFO ][o.e.c.m.MetaDataCreateIndexService] [JHSGgjI] [geonames] creating index, cause [api], templates [], shards [5]/[0], mappings [geonameEntry, _default_]
[2018-03-06T00:40:15,141][INFO ][o.e.c.r.a.AllocationService] [JHSGgjI] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[geonames][4]] ...]).
19859 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ConditionESQueryBuilderIT
20334 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.SegmentIT
20389 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ProfileServiceIT
20439 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ProfileImportBasicIT
[2018-03-06T00:40:16,193][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] create_mapping [importConfig]


        ____ ___     A P A C H E     .__
       |    |   \____   ____   _____ |__|
       |    |   /    \ /  _ \ /     \|  |
       |    |  /   |  (  <_> )  Y Y  \  |
       |______/|___|  /\____/|__|_|  /__|
                    \/             \/

--------------------------------------------------------------------------
  1.3.0.incubating-unomi_5_karaf4_1-SNAPSHOT  Build:67a63  Timestamp:1520293108397
--------------------------------------------------------------------------
Successfully started 24 bundles and 2 required services in 12874 ms
[2018-03-06T00:41:18,845][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [importConfig]
[2018-03-06T00:41:22,583][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [profile]
100701 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ProfileImportSurfersIT
[2018-03-06T00:41:36,435][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [propertyType]
[2018-03-06T00:41:46,542][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [importConfig]
[2018-03-06T00:41:47,597][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [profile]
161037 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ProfileImportRankingIT
[2018-03-06T00:42:46,820][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [importConfig]
[2018-03-06T00:42:52,630][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [profile]
181133 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ProfileImportActorsIT
[2018-03-06T00:43:06,981][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [importConfig]
[2018-03-06T00:43:12,633][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [profile]
201302 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ProfileExportIT
[2018-03-06T00:43:17,032][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [segment]
[2018-03-06T00:43:27,112][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] create_mapping [exportConfig]
[2018-03-06T00:43:28,140][INFO ][o.e.c.m.MetaDataMappingService] [JHSGgjI] [context/ymhfrAJxQxa_CxM1joCeeQ] update_mapping [exportConfig]
221423 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.PropertiesUpdateActionIT
221523 [main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.unomi.itests.ModifyConsentIT
221552 [main] INFO org.ops4j.pax.exam.spi.reactors.ReactorManager - suite finished
[ERROR] Tests run: 20, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 224.42 s <<< FAILURE! - in org.apache.unomi.itests.AllITs
[ERROR] testUpdateProperties_CurrentProfile(org.apache.unomi.itests.PropertiesUpdateActionIT)  Time elapsed: 0.069 s  <<< FAILURE!
java.lang.AssertionError
	at org.apache.unomi.itests.PropertiesUpdateActionIT.testUpdateProperties_CurrentProfile(PropertiesUpdateActionIT.java:88)

[ERROR] testUpdateProperties_NotCurrentProfile(org.apache.unomi.itests.PropertiesUpdateActionIT)  Time elapsed: 0.03 s  <<< FAILURE!
java.lang.AssertionError: expected:<UPDATED FIRST NAME> but was:<null>
	at org.apache.unomi.itests.PropertiesUpdateActionIT.testUpdateProperties_NotCurrentProfile(PropertiesUpdateActionIT.java:112)

[ERROR] testConsentGrant(org.apache.unomi.itests.ModifyConsentIT)  Time elapsed: 0.028 s  <<< FAILURE!
java.lang.AssertionError
	at org.apache.unomi.itests.ModifyConsentIT.testConsentGrant(ModifyConsentIT.java:88)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ModifyConsentIT.testConsentGrant:88
[ERROR]   PropertiesUpdateActionIT.testUpdateProperties_CurrentProfile:88
[ERROR]   PropertiesUpdateActionIT.testUpdateProperties_NotCurrentProfile:112 expected:<UPDATED FIRST NAME> but was:<null>
[INFO] 
[ERROR] Tests run: 20, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by sergehuber** [comment]
Thanks a lot for all the changes, I've reviewed them and they do indeed seem to help a lot. I've investigated into the test failures and it seems that some services are not registering properly which is strange because in the Karaf custom distribution they work fine. Not sure what is going on there (yet).

**Comment by sergehuber** [comment]
Ok I found the problem, some mistakes I introduced in the Blueprint descriptors. After correcting it I had a successful run of all the integration tests ! Thanks a lot for all the work Oliver it is highly appreciated !

**Comment by sergehuber** [comment]
Thanks a lot Oliver, I've merged the PR and will commit the changes to get all the tests working next.

**Pull request merged**
