### PR TITLE
Fix Kar feature deployment in Karaf 4.2.x

### PR DESCRIPTION
**Pull request by fpapon**
This is a PR for fixing kar deployment in a fresh Karaf 4.2.x instance.

It's temporary before having the next major refactor for Karaf 4.x.

### CODE REVIEW

**Comment by sergehuber** [comment]
Thanks for the PR.

Does this work with Karaf 4.1 also ?

Regards,
  Serge...

**Comment by fpapon** [comment]
I have an error (both on 4.2.2 and 4.1.7) but I think it's not related to this PR:

```
com.hazelcast.config.InvalidConfigurationException: cvc-datatype-valid.1.2.1 : '${org.apache.unomi.hazelcast.network.port}' n'est pas une valeur valide pour 'integer'.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:189) ~[57:com.hazelcast:3.8.1]
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:232) ~[57:com.hazelcast:3.8.1]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:213) ~[57:com.hazelcast:3.8.1]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:206) ~[57:com.hazelcast:3.8.1]
	at org.apache.karaf.cellar.hazelcast.factory.HazelcastConfigurationManager.getHazelcastConfig(HazelcastConfigurationManager.java:51) ~[127:org.apache.karaf.cellar.hazelcast:4.1.0]
	at org.apache.karaf.cellar.hazelcast.factory.HazelcastServiceFactory.buildInstance(HazelcastServiceFactory.java:77) ~[127:org.apache.karaf.cellar.hazelcast:4.1.0]
	at org.apache.karaf.cellar.hazelcast.factory.HazelcastServiceFactory.getInstance(HazelcastServiceFactory.java:62) ~[127:org.apache.karaf.cellar.hazelcast:4.1.0]
	at org.apache.karaf.cellar.hazelcast.internal.osgi.Activator.doStart(Activator.java:168) ~[127:org.apache.karaf.cellar.hazelcast:4.1.0]
	at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:242) [127:org.apache.karaf.cellar.hazelcast:4.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by sergehuber** [comment]
Ok it seems like there is a problem with the new system properties. Can you check if you have the property in custom.system.properties ?

**Comment by fpapon** [comment]
Ok I see, I just installed the kar feature in a fresh Karaf instance, so I missed all the custom files included in the custom distribution ;)

**Comment by sergehuber** [comment]
Ok I merged the PR, sorry it took so long !

**Pull request merged**
